### ISSUE TITLE
Vuze support

### ISSUE THREAD

**Issue by eloitay** [BoKKeR/TorrentSwitch#3]
Hi
It would be nice if we can have Vuze support.

**Comment by BoKKeR** [comment]
I will look into it. There is a json based API so it should be as the other clients.

**Comment by BoKKeR** [comment]
The newest release supports Vuze for adding torrents. Labels and the custom paths are still not supported. You will need the WebUI plugin to get it to work: http://plugins.vuze.com/details/xmwebui
